const data = [
  {
    id: 1,
    title: "Omlet",
    category: "Kahvaltılık",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio, enim.",
  },
  {
    id: 2,
    title: "Kuzu Sarma",
    category: "Öğle Yemeği",
    price: 43.99,
    img: "./images/item-2.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo earum saepe est!",
  },
  {
    id: 3,
    title: "Alman Pastası",
    category: "Atıştırmalık",
    price: 16.99,
    img: "./images/item-3.jpeg",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 4,
    title: "Gözleme",
    category: "Kahvaltılık",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti accusantium officia commodi minus aut aliquid harum.",
  },
  {
    id: 5,
    title: " Urfa Kebap",
    category: "Öğle Yemeği",
    price: 42.99,
    img: "./images/item-5.jpeg",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa numquam placeat officia tenetur nulla adipisci.",
  },
  {
    id: 6,
    title: "Tost",
    category: "Atıştırmalık",
    price: 21.99,
    img: "./images/item-6.jpeg",
    desc: "Lorem ipsum dolor sit amet.",
  },
  {
    id: 7,
    title: "Patates Kızartması",
    category: "Kahvaltılık",
    price: 18.99,
    img: "./images/item-7.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita.",
  },
  {
    id: 8,
    title: "Tavuk Sote",
    category: "Öğle Yemeği",
    price: 32.99,
    img: "./images/item-8.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta sit obcaecati eaque neque",
  },
  {
    id: 9,
    title: "Türk Kahvesi",
    category: "Atıştırmalık",
    price: 22.99,
    img: "./images/item-8.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
];
export default data;
